const presetMap: {[key: string]: string} = {
    "ancient_city": "https://minecraft.wiki/images/Invicon_Echo_Shard.png?1c720",
    "apricorns": "https://gitlab.com/cable-mc/cobblemon/-/raw/main/common/src/main/resources/assets/cobblemon/textures/item/red_apricorn.png?ref_type=heads",
    "blue_flowers": "https://minecraft.wiki/images/Invicon_Cornflower.png?597ea",
    "derelict": "https://minecraft.wiki/images/Invicon_Coarse_Dirt.png?9cd20",
    "desert_pyramid": "https://minecraft.wiki/images/Invicon_Sandstone.png?0782d",
    "end_city": "https://minecraft.wiki/images/Invicon_Shulker_Shell.png?b1594",
    "flowers": "https://minecraft.wiki/images/Invicon_Rose_Bush.png?adcb3&format=original",
    "foliage": "https://minecraft.wiki/images/Invicon_Vines.png?ac12d",
    "freshwater": "https://minecraft.wiki/images/Invicon_Raw_Cod.png?d2bf9",  
    "gemstones": "https://minecraft.wiki/images/Invicon_Amethyst_Cluster.png?a17fa&format=original",
    "illager_structures": "https://minecraft.wiki/images/Invicon_Ominous_Banner.png?6fa92",
    "jungle_pyramid": "https://minecraft.wiki/images/Invicon_Tripwire_Hook.png?b67d4",
    "lava_surface": "https://minecraft.wiki/images/Invicon_Magma_Block.gif?3e0e8",
    "mansion": "https://minecraft.wiki/images/Invicon_Totem_of_Undying.png?ad7ee",
    "natural": "https://minecraft.wiki/images/Invicon_Grass_Block.png?a5d1f",
    "nether_fossil": "https://minecraft.wiki/images/Invicon_Bone.png?d8310",
    "nether_structures": "https://minecraft.wiki/images/Invicon_Blaze_Powder.png?ac8b4",
    "ocean_monument": "https://minecraft.wiki/images/Invicon_Sponge.png?ab3bd",
    "ocean_ruins": "https://minecraft.wiki/images/Invicon_Prismarine_Shard.png?79730",
    "orange_flowers": "https://minecraft.wiki/images/Invicon_Torchflower.png?3f1ab",
    "pillager_outpost": "https://minecraft.wiki/images/Invicon_Crossbow.png?3188b",
    "pink_flowers": "https://minecraft.wiki/images/Invicon_Pink_Daisy.png?29e41&format=original", 
    "red_flowers": "https://minecraft.wiki/images/Invicon_Poppy.png?c109d",
    "redstone": "https://minecraft.wiki/images/Invicon_Redstone.png?26ec3",
    "river": "https://minecraft.wiki/images/Invicon_Clay.png?21b54",
    "ruined_portal": "https://minecraft.wiki/images/Invicon_Crying_Obsidian.png?eb75b",
    "ruins": "https://minecraft.wiki/images/Invicon_Suspicious_Gravel.png?28062",
    "salt": "https://minecraft.wiki/images/Invicon_Sugar.png?2d377",
    "shipwreck": "https://minecraft.wiki/images/Invicon_Map.png?24187",
    "stronghold": "https://minecraft.wiki/images/Invicon_Eye_of_Ender.png?d24aa",
    "trail_ruins": "https://minecraft.wiki/images/Invicon_Brush.png?afa3f",
    "trash": "https://minecraft.wiki/images/Invicon_Venomous_Potato.png?2a2e6",
    "treetop": "https://minecraft.wiki/images/Invicon_Oak_Sapling.png?86bec",
    "underground_ruins": "https://minecraft.wiki/images/Trial_Key_JE2_BE2.png?a203a", 
    "underlava": "https://minecraft.wiki/images/BlockSprite_lava.png?e9467",
    "underwater": "https://minecraft.wiki/images/BlockSprite_stationary-water.png?1dce1",
    "urban": "https://minecraft.wiki/images/Invicon_Yellow_Concrete.png?8a350",  
    "village": "https://minecraft.wiki/images/Invicon_Oak_Door.png?1d87c",
    "water_surface": "https://minecraft.wiki/images/Invicon_Lily_Pad.png?01171",
    "webs": "https://minecraft.wiki/images/Invicon_Cobweb.png?cb28b&format=original",
    "white_flowers": "https://minecraft.wiki/images/Invicon_White_Tulip.png", 
    "wild": "https://minecraft.wiki/images/Invicon_Short_Grass.png?e5583", 
    "yellow_flowers": "https://minecraft.wiki/images/Invicon_Dandelion.png?7bba3"
}

export default presetMap